@baseUrl = http://127.0.0.1:3000

# Recados
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=100
&offset=300

### Lista apenas um recado
GET {{baseUrl}}/recados/2/
### Cria um recado

POST {{baseUrl}}/recados
Content-Type: application/json

{
    "text": "Novo recado",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2025-10-04T18:31:52.729Z"
}

### Atualiza um recado
PATCH  {{baseUrl}}/recados/2/
Content-Type: application/json

{
    "text": "Editando recando",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2025-10-04T18:31:52.729Z"
}

### Remove  um recado
DELETE {{baseUrl}}/recados/2/
### Cria um recado

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo

### ConceitosManualController Home

# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual

### ConceitosManualController Home

# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico